//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Accumulators
    {
        public string PN { get; set; }
        public string MaterialNumber { get; set; }
        public string QuoteDescription { get; set; }
        public Nullable<double> StandardPrice { get; set; }
        public string MG2 { get; set; }
        public string Class { get; set; }
        public string info1 { get; set; }
        public string info2 { get; set; }
        public string info3 { get; set; }
        public string info4 { get; set; }
        public string info5 { get; set; }
        public string info6 { get; set; }
        public string info7 { get; set; }
        public string info8 { get; set; }
        public string info9 { get; set; }
        public string info10 { get; set; }
        public int AccumulatorId { get; set; }
    }
}
