//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ANSIPiping
    {
        public int PipingId { get; set; }
        public string SAP_m_n { get; set; }
        public string SAP_Description { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> SAP_Cost { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Conduit { get; set; }
        public string Units { get; set; }
        public string Material { get; set; }
        public string Joint { get; set; }
        public string Size { get; set; }
        public string Size_Unit { get; set; }
        public string Schedule { get; set; }
        public string Component { get; set; }
        public string Type { get; set; }
        public string Paint_Requirement { get; set; }
        public Nullable<double> Weld_Time { get; set; }
        public Nullable<double> Cut_Prep { get; set; }
        public Nullable<double> Assemble { get; set; }
        public Nullable<decimal> MTL1 { get; set; }
        public Nullable<decimal> MTL2 { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<double> HrsWeld { get; set; }
        public Nullable<double> HrsAssy { get; set; }
        public string Schem_Component { get; set; }
        public Nullable<decimal> MTLsub { get; set; }
    }
}
