//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Contact_Information
    {
        public int Auto { get; set; }
        public Nullable<int> Quote_Auto { get; set; }
        public string contact_salutation { get; set; }
        public string contact_fname { get; set; }
        public string contact_lname { get; set; }
        public string contact_telbus { get; set; }
        public string contact_telmobile { get; set; }
        public string contact_telfax { get; set; }
        public string contact_email { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
