//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Custom_Customers
    {
        public int Auto { get; set; }
        public Nullable<int> Quote_Auto { get; set; }
        public Nullable<int> Customer_Type { get; set; }
        public string Cust_Name { get; set; }
        public string Cust_Street { get; set; }
        public string Cust_City { get; set; }
        public string Cust_Zip { get; set; }
        public string Cust_State { get; set; }
        public string Cust_Country { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> IsValidCustType { get; set; }
    }
}
