//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Fields_Value
    {
        public int FieldValueId { get; set; }
        public Nullable<int> FieldId { get; set; }
        public string FieldValueName { get; set; }
        public string FieldValueDescription { get; set; }
        public Nullable<int> FieldValueNameId { get; set; }
    
        public virtual T_Fields T_Fields { get; set; }
    }
}
