//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Flanges
    {
        public string PN { get; set; }
        public string MaterialNumber { get; set; }
        public string QuoteDescription { get; set; }
        public Nullable<double> StandardPrice { get; set; }
        public string MG2 { get; set; }
        public string Class { get; set; }
        public string INFO1 { get; set; }
        public string INFO2 { get; set; }
        public string INFO3 { get; set; }
        public string INFO4 { get; set; }
        public string INFO5 { get; set; }
        public string INFO6 { get; set; }
        public string INFO7 { get; set; }
        public int FlangeId { get; set; }
    }
}
