//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Labor
    {
        public int QN { get; set; }
        public int SN { get; set; }
        public Nullable<decimal> engineering { get; set; }
        public Nullable<decimal> design { get; set; }
        public Nullable<decimal> assembly { get; set; }
        public Nullable<decimal> wiring { get; set; }
        public Nullable<decimal> welding { get; set; }
        public Nullable<decimal> test { get; set; }
        public Nullable<decimal> paint { get; set; }
        public Nullable<decimal> documentation { get; set; }
        public Nullable<decimal> labor_total { get; set; }
        public Nullable<int> labor_margin { get; set; }
        public Nullable<decimal> labor_net_total { get; set; }
        public int auto { get; set; }
        public Nullable<double> WiringDesign { get; set; }
        public Nullable<double> TestHydraulic { get; set; }
        public Nullable<double> TestSound { get; set; }
        public Nullable<double> TestVibration { get; set; }
        public Nullable<double> ShippingTag { get; set; }
        public Nullable<double> PickParts { get; set; }
        public Nullable<double> TotalLaborDollars { get; set; }
        public Nullable<double> TotalLabor { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SubassemblyID { get; set; }
        public Nullable<double> ControlsEngineering { get; set; }
        public Nullable<double> Programming { get; set; }
        public Nullable<double> IM_Machining_Man { get; set; }
        public Nullable<double> IM_Machining_CNC { get; set; }
    
        public virtual T_Quotes T_Quotes { get; set; }
    }
}
