//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_labor_variables
    {
        public int auto { get; set; }
        public Nullable<decimal> Engineering { get; set; }
        public Nullable<decimal> design { get; set; }
        public Nullable<decimal> assembly { get; set; }
        public Nullable<decimal> wiring { get; set; }
        public Nullable<decimal> welding { get; set; }
        public Nullable<decimal> test { get; set; }
        public Nullable<decimal> paint { get; set; }
        public Nullable<decimal> documentation { get; set; }
        public Nullable<decimal> WiringDesign { get; set; }
        public Nullable<decimal> PickParts { get; set; }
        public Nullable<decimal> ShippingTag { get; set; }
    }
}
