//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LABOR_DATA_Tmp
    {
        public int QN { get; set; }
        public int SN { get; set; }
        public Nullable<long> DTMPQTY { get; set; }
        public Nullable<long> DTMEQTY { get; set; }
        public Nullable<long> TDRC { get; set; }
        public Nullable<long> TDNC { get; set; }
        public Nullable<long> LDLQQTY { get; set; }
        public Nullable<long> COMPACCPUA { get; set; }
        public Nullable<long> COMPACCSPEC { get; set; }
        public Nullable<long> COMBREPUA { get; set; }
        public Nullable<long> COMBRESPEC { get; set; }
        public Nullable<long> COMCLEPUA { get; set; }
        public Nullable<long> COMCLESPEC { get; set; }
        public Nullable<long> COMFILPUA { get; set; }
        public Nullable<long> COMFILSPEC { get; set; }
        public Nullable<long> COMFLSWPUA { get; set; }
        public Nullable<long> COMFLSWSPEC { get; set; }
        public Nullable<long> COMGUAPUA { get; set; }
        public Nullable<long> COMGUASPEC { get; set; }
        public Nullable<long> COMGPPUA { get; set; }
        public Nullable<long> COMGPSPEC { get; set; }
        public Nullable<long> COMHEAPUA { get; set; }
        public Nullable<long> COMHEASPEC { get; set; }
        public Nullable<long> COMAHEPUA { get; set; }
        public Nullable<long> COMAHESPEC { get; set; }
        public Nullable<long> COMWHEPUA { get; set; }
        public Nullable<long> COMWHESPEC { get; set; }
        public Nullable<long> COMHOSPUA { get; set; }
        public Nullable<long> COMHOSSPEC { get; set; }
        public Nullable<long> COMMMPUA { get; set; }
        public Nullable<long> COMMMSPEC { get; set; }
        public Nullable<long> COMSVPUA { get; set; }
        public Nullable<long> COMSVSPEC { get; set; }
        public Nullable<long> COMSGPUA { get; set; }
        public Nullable<long> COMSGSPEC { get; set; }
        public Nullable<long> COMVPPUA { get; set; }
        public Nullable<long> COMVPSPEC { get; set; }
        public Nullable<long> COMTSPUA { get; set; }
        public Nullable<long> COMTSSPEC { get; set; }
        public Nullable<long> COMTPUA { get; set; }
        public Nullable<long> COMTSPEC { get; set; }
        public Nullable<long> MPGCC1 { get; set; }
        public Nullable<long> MPGCC2 { get; set; }
        public Nullable<long> MPGCC3 { get; set; }
        public Nullable<long> MPGCC4 { get; set; }
        public Nullable<long> MPGHB1 { get; set; }
        public Nullable<long> MPGHB2 { get; set; }
        public Nullable<long> MPGHB3 { get; set; }
        public Nullable<long> MPGHB4 { get; set; }
        public Nullable<long> MPGHB5 { get; set; }
        public Nullable<long> MPGVB1 { get; set; }
        public Nullable<long> MPGVB2 { get; set; }
        public Nullable<long> MPGVB3 { get; set; }
        public Nullable<long> MPGVB4 { get; set; }
        public Nullable<long> MPGVB5 { get; set; }
        public Nullable<long> MPGVS1 { get; set; }
        public Nullable<long> MPGVS2 { get; set; }
        public Nullable<long> MPGVS3 { get; set; }
        public Nullable<long> MPGVS4 { get; set; }
        public Nullable<long> MPGVS5 { get; set; }
        public string ResType { get; set; }
        public Nullable<int> ElecConnections { get; set; }
        public Nullable<bool> SoundTestFlowAndPressure { get; set; }
        public Nullable<bool> SoundTestFlow { get; set; }
        public Nullable<bool> SoundTestDeadhead { get; set; }
        public Nullable<bool> VibrationTestFlowAndPressure { get; set; }
        public Nullable<bool> VibrationTestFlow { get; set; }
        public Nullable<bool> VibrationTestDeadhead { get; set; }
        public Nullable<short> VibrationNumTestPoints { get; set; }
        public Nullable<bool> CustomerTitleBlock { get; set; }
        public Nullable<bool> SpecialDimensioning { get; set; }
        public Nullable<short> ResStyle { get; set; }
        public Nullable<bool> ComplexSchematic { get; set; }
        public Nullable<short> LabelType { get; set; }
        public Nullable<short> CustomerWitness { get; set; }
        public Nullable<short> CableType { get; set; }
        public Nullable<bool> CableExplosion { get; set; }
        public Nullable<short> CableQty { get; set; }
        public Nullable<short> FittingType { get; set; }
        public Nullable<short> Fitting1Qty { get; set; }
        public Nullable<short> Fitting2Qty { get; set; }
        public Nullable<short> Fitting3Qty { get; set; }
        public Nullable<short> Fitting4Qty { get; set; }
        public Nullable<short> PanelMtdValvesStd { get; set; }
        public Nullable<short> PanelMtdValvesNonStd { get; set; }
        public Nullable<short> ElecBoxStd { get; set; }
        public Nullable<short> ElecBoxNonStd { get; set; }
        public Nullable<int> auto { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SubassemblyID { get; set; }
        public Nullable<double> Adjustengineering { get; set; }
        public Nullable<double> Adjustdesign { get; set; }
        public Nullable<double> AdjustWiringDesign { get; set; }
        public Nullable<double> AdjustPickParts { get; set; }
        public Nullable<double> Adjustwiring { get; set; }
        public Nullable<double> Adjustwelding { get; set; }
        public Nullable<double> Adjusttest { get; set; }
        public Nullable<double> AdjustShippingTag { get; set; }
        public Nullable<double> Adjustpaint { get; set; }
        public Nullable<double> Adjustdocumentation { get; set; }
        public Nullable<double> Adjustassembly { get; set; }
        public Nullable<double> AdjustControlsEngineering { get; set; }
        public Nullable<double> AdjustProgramming { get; set; }
        public Nullable<double> AdjustIM_Machining_Man { get; set; }
        public Nullable<double> AdjustIM_Machining_Cnc { get; set; }
        public Nullable<double> AdjustAssemblyHoursNonSAPPiping { get; set; }
        public Nullable<double> AdjustEngineeringHoursNonSAPPiping { get; set; }
        public Nullable<double> AdjustDesignHoursNonSAPPiping { get; set; }
        public Nullable<double> AdjustPaintHoursNonSAPPiping { get; set; }
        public Nullable<double> AdjustWeldingHoursNonSAPPiping { get; set; }
        public string AdjustDescriptionDetails { get; set; }
        public string NonAdjustDescriptionDetails { get; set; }
    }
}
