//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PipingLaborConfiguration
    {
        public int Id { get; set; }
        public string Conduit { get; set; }
        public string Component { get; set; }
        public string Type { get; set; }
        public string Material { get; set; }
        public string Joint { get; set; }
        public string Schedule { get; set; }
        public double MinSize { get; set; }
        public double MaxSize { get; set; }
        public double AssemblyLaborHours { get; set; }
        public double WeldingLaborHours { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
