//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PipingComponents
    {
        public int ID { get; set; }
        public string Component_Name { get; set; }
        public Nullable<bool> flgActive { get; set; }
        public string Url { get; set; }
    }
}
