//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Piping_PaintDetail
    {
        public int PaintID { get; set; }
        public string Paint_Type { get; set; }
        public string Paint_Description { get; set; }
        public Nullable<double> value { get; set; }
        public string metal_type { get; set; }
        public Nullable<bool> flgStatus { get; set; }
    }
}
