//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PipingLabor_Data_Tmp
    {
        public int Id { get; set; }
        public Nullable<int> QN { get; set; }
        public Nullable<int> SN { get; set; }
        public Nullable<int> subassemblyid { get; set; }
        public string Conduit { get; set; }
        public string Unit { get; set; }
        public string Material { get; set; }
        public string Joint { get; set; }
        public string Paint_Details { get; set; }
        public string Method { get; set; }
        public string component { get; set; }
        public string size { get; set; }
        public string schedule { get; set; }
        public string Type { get; set; }
        public Nullable<int> PackageQty { get; set; }
        public Nullable<int> PartQty { get; set; }
        public string PN { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> PipingPackageID { get; set; }
    }
}
