//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PipingLaborForCSSS
    {
        public int Id { get; set; }
        public string Schedule { get; set; }
        public double MinSize { get; set; }
        public double MaxSize { get; set; }
        public double AssemblyHours { get; set; }
        public double WeldingHours { get; set; }
    }
}
