//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_qts_tblPUAdescr
    {
        public string SHEET_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public string SECT { get; set; }
        public string FILENAME { get; set; }
        public string Field5 { get; set; }
        public int Auto { get; set; }
    }
}
