//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Quotes
    {
        public T_Quotes()
        {
            this.T_Labor = new HashSet<T_Labor>();
            this.T_LABOR_DATA = new HashSet<T_LABOR_DATA>();
            this.T_Quote_Sections = new HashSet<T_Quote_Sections>();
            this.T_Quote_Sub = new HashSet<T_Quote_Sub>();
        }
    
        public int auto { get; set; }
        public string Quote_number { get; set; }
        public short Quote_Revision { get; set; }
        public System.DateTime quote_expectedorder_date { get; set; }
        public Nullable<System.DateTime> quote_rec_date { get; set; }
        public Nullable<System.DateTime> quote_due_date { get; set; }
        public Nullable<System.DateTime> quote_issued_date { get; set; }
        public Nullable<int> sales_office { get; set; }
        public Nullable<int> sales_group { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public string cust_sap_number { get; set; }
        public string contact_salutation { get; set; }
        public string contact_fname { get; set; }
        public string contact_lname { get; set; }
        public string contact_telbus { get; set; }
        public string contact_telmobile { get; set; }
        public string contact_telfax { get; set; }
        public string contact_email { get; set; }
        public string description { get; set; }
        public Nullable<double> est_price { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> LineItemIncrement { get; set; }
        public Nullable<int> TechPositionIncrement { get; set; }
        public string Reason { get; set; }
        public string ReasonDetails { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<int> SalesOrderNumber { get; set; }
        public int CustomerType { get; set; }
        public int flgCustomBillCust { get; set; }
        public int flgCustomOEMUser { get; set; }
        public int ProbabilityPO { get; set; }
        public int ProbabilityEOD { get; set; }
    
        public virtual ICollection<T_Labor> T_Labor { get; set; }
        public virtual ICollection<T_LABOR_DATA> T_LABOR_DATA { get; set; }
        public virtual ICollection<T_Quote_Sections> T_Quote_Sections { get; set; }
        public virtual ICollection<T_Quote_Sub> T_Quote_Sub { get; set; }
    }
}
