//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Quote_Sub
    {
        public Nullable<int> SN { get; set; }
        public Nullable<int> LI { get; set; }
        public Nullable<int> qty { get; set; }
        public string pn { get; set; }
        public string tp { get; set; }
        public string descr { get; set; }
        public Nullable<decimal> net_cost { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<double> part_markup { get; set; }
        public string revision { get; set; }
        public int auto { get; set; }
        public string sub_descr { get; set; }
        public int QN { get; set; }
        public Nullable<double> PipingWelding { get; set; }
        public Nullable<double> PipingAssembly { get; set; }
        public string UserDesc { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsCostChanged { get; set; }
        public string InternalNote { get; set; }
        public Nullable<bool> IsCostIncrease { get; set; }
        public Nullable<double> SAPCost { get; set; }
        public Nullable<double> SAPNetCost { get; set; }
    
        public virtual T_Quotes T_Quotes { get; set; }
    }
}
