//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Quote_Sections
    {
        public int QN { get; set; }
        public string section { get; set; }
        public Nullable<int> SN { get; set; }
        public string descr { get; set; }
        public Nullable<double> section_markup { get; set; }
        public string part_number { get; set; }
        public string sap_descr { get; set; }
        public string revision { get; set; }
        public Nullable<double> section_cost { get; set; }
        public Nullable<double> sect_net_cost { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<double> DefaultPartMargin { get; set; }
        public Nullable<decimal> plantadministration { get; set; }
        public Nullable<decimal> manufacturingcost { get; set; }
        public Nullable<decimal> sga { get; set; }
        public Nullable<decimal> riskfactor { get; set; }
        public Nullable<decimal> sellprice { get; set; }
        public Nullable<decimal> labor_tot { get; set; }
        public Nullable<decimal> commission { get; set; }
        public Nullable<decimal> materialoverhead { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int auto { get; set; }
        public Nullable<int> SectionOrder { get; set; }
        public Nullable<double> RiskFactorPercentage { get; set; }
        public Nullable<double> SGAPercentage { get; set; }
    
        public virtual T_Quotes T_Quotes { get; set; }
    }
}
