//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Quote_Details
    {
        public int Quote_UserId { get; set; }
        public int Quote_auto { get; set; }
        public Nullable<int> Application_Engineer { get; set; }
        public Nullable<int> Sale_Engineer { get; set; }
        public Nullable<int> Distribution_Channel { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Cost_Approver { get; set; }
        public Nullable<System.DateTime> CA_Action_Date { get; set; }
        public string CA_Comment { get; set; }
        public Nullable<int> Sell_Price_Approver { get; set; }
        public Nullable<System.DateTime> SPA_Action_Date { get; set; }
        public string SPA_Comment { get; set; }
        public Nullable<int> Additional_SP_Approver { get; set; }
        public Nullable<System.DateTime> ASPA_Action_Date { get; set; }
        public string ASPA_Comment { get; set; }
        public Nullable<short> Approval_Levels { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string IsPMEffort { get; set; }
        public Nullable<decimal> PMEffort { get; set; }
        public string IsCommission { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<int> PreviousStatusId { get; set; }
    }
}
