//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Quote_Parts_Tmp
    {
        public string sub { get; set; }
        public Nullable<int> SN { get; set; }
        public Nullable<int> LI { get; set; }
        public Nullable<int> qty { get; set; }
        public string PN { get; set; }
        public string TP { get; set; }
        public string descr { get; set; }
        public Nullable<decimal> net_cost { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<double> part_markup { get; set; }
        public string revision { get; set; }
        public Nullable<int> auto { get; set; }
        public int QN { get; set; }
        public Nullable<double> PipingWelding { get; set; }
        public Nullable<double> PipingAssembly { get; set; }
        public Nullable<decimal> materialoverhead { get; set; }
        public Nullable<decimal> plantadministration { get; set; }
        public Nullable<decimal> manufacturingcost { get; set; }
        public Nullable<decimal> sga { get; set; }
        public Nullable<decimal> riskfactor { get; set; }
        public Nullable<decimal> sellprice { get; set; }
        public Nullable<long> CopyFrom { get; set; }
        public string UserDesc { get; set; }
        public Nullable<int> ShippableAssemblyId { get; set; }
        public Nullable<int> SubOrder { get; set; }
        public bool IsCostChanged { get; set; }
        public string InternalNote { get; set; }
        public Nullable<bool> IsCostIncrease { get; set; }
        public Nullable<double> SAPCost { get; set; }
        public Nullable<double> SAPNetCost { get; set; }
    }
}
