//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ResInfo
    {
        public int Id { get; set; }
        public string ResType { get; set; }
        public Nullable<int> PartsListTime { get; set; }
        public Nullable<double> PickPartsTime { get; set; }
        public Nullable<int> WiringBasicTime { get; set; }
        public Nullable<double> BasicAssemblyTime { get; set; }
        public Nullable<double> DesignHours { get; set; }
        public Nullable<int> AssemblyDrawingMinutes { get; set; }
        public Nullable<int> SchematicReview { get; set; }
        public Nullable<int> ComponentAssemblyMultiplier { get; set; }
        public Nullable<double> BasicPaintTime { get; set; }
        public Nullable<int> ReservoirCapacityInGallons { get; set; }
    }
}
