//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SalesOffice
    {
        public T_SalesOffice()
        {
            this.T_sap_customer = new HashSet<T_sap_customer>();
        }
    
        public int SalesOfficeID { get; set; }
        public string SalesOfficeName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<T_sap_customer> T_sap_customer { get; set; }
    }
}
