//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_sapmats
    {
        public int ID { get; set; }
        public string Material { get; set; }
        public string Material_number { get; set; }
        public Nullable<int> PGr { get; set; }
        public string Purchasing_group { get; set; }
        public Nullable<int> MRPCn { get; set; }
        public string MRP_controller { get; set; }
        public string MS { get; set; }
        public string Plant_Specific_Material_Status { get; set; }
        public Nullable<int> Product_hierarchy { get; set; }
        public string Field11 { get; set; }
        public Nullable<double> Total_stock { get; set; }
        public string BUn { get; set; }
        public Nullable<decimal> Standard_price { get; set; }
        public Nullable<double> Comsumption { get; set; }
        public string MG_2 { get; set; }
        public string Material_group_2 { get; set; }
    }
}
