//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ShippableAssembly
    {
        public T_ShippableAssembly()
        {
            this.T_LaborCostFactors_ShippableAssembly = new HashSet<T_LaborCostFactors_ShippableAssembly>();
        }
    
        public int ShippableAssemblyID { get; set; }
        public string ShippableAssemblyName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> flgActive { get; set; }
    
        public virtual ICollection<T_LaborCostFactors_ShippableAssembly> T_LaborCostFactors_ShippableAssembly { get; set; }
    }
}
