//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UserRoles
    {
        public int UserRoleId { get; set; }
        public int AppRoleId { get; set; }
        public int UserId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual T_AppRole T_AppRole { get; set; }
        public virtual T_Users T_Users { get; set; }
    }
}
